// Code generated by protoc-gen-go.
// source: git.oschina.net/wkc/book-server-v2/proto/v1/BookService.proto
// DO NOT EDIT!

/*
Package go_micro_srv_book_server_v2 is a generated protocol buffer package.

It is generated from these files:
	git.oschina.net/wkc/book-server-v2/proto/v1/BookService.proto

It has these top-level messages:
	GetTagsRequest
	GetTagsResponse
	GetTagByIdRequest
	Book
	GetTagByIdResponse
	GetBookByIdRequest
	GetBookByIdResponse
	GetBookContentRequest
	GetBookContentResponse
	SearchBookRequest
	SearchBookResponse
	RegisterRequest
	RegisterResponse
	LoginRequest
	LoginResponse
	User
	GetUserInfoRequest
	GetUserInfoResponse
	CollectBookRequest
	CollectBookResponse
	GetCollectedBookRequest
	GetCollectedBookResponse
	SetUserReadStatusRequest
	SetUserReadStatusResponse
	GetUserReadStatusRequest
	GetUserReadStatusResponse
	GetUserRecommendBookRequest
	GetUserRecommendBookResponse
*/
package go_micro_srv_book_server_v2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetTagsRequest struct {
}

func (m *GetTagsRequest) Reset()                    { *m = GetTagsRequest{} }
func (m *GetTagsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTagsRequest) ProtoMessage()               {}
func (*GetTagsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetTagsResponse struct {
	Tags []*GetTagsResponse_Tag `protobuf:"bytes,1,rep,name=tags" json:"tags,omitempty"`
}

func (m *GetTagsResponse) Reset()                    { *m = GetTagsResponse{} }
func (m *GetTagsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTagsResponse) ProtoMessage()               {}
func (*GetTagsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetTagsResponse) GetTags() []*GetTagsResponse_Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type GetTagsResponse_Tag struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	BooksCnt int32  `protobuf:"varint,3,opt,name=books_cnt,json=booksCnt" json:"books_cnt,omitempty"`
}

func (m *GetTagsResponse_Tag) Reset()                    { *m = GetTagsResponse_Tag{} }
func (m *GetTagsResponse_Tag) String() string            { return proto.CompactTextString(m) }
func (*GetTagsResponse_Tag) ProtoMessage()               {}
func (*GetTagsResponse_Tag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *GetTagsResponse_Tag) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetTagsResponse_Tag) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *GetTagsResponse_Tag) GetBooksCnt() int32 {
	if m != nil {
		return m.BooksCnt
	}
	return 0
}

type GetTagByIdRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetTagByIdRequest) Reset()                    { *m = GetTagByIdRequest{} }
func (m *GetTagByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTagByIdRequest) ProtoMessage()               {}
func (*GetTagByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetTagByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Book struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Picture     string `protobuf:"bytes,3,opt,name=picture" json:"picture,omitempty"`
	Author      string `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Category    string `protobuf:"bytes,6,opt,name=category" json:"category,omitempty"`
}

func (m *Book) Reset()                    { *m = Book{} }
func (m *Book) String() string            { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()               {}
func (*Book) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Book) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Book) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Book) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type GetTagByIdResponse struct {
	Books []*Book `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
}

func (m *GetTagByIdResponse) Reset()                    { *m = GetTagByIdResponse{} }
func (m *GetTagByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTagByIdResponse) ProtoMessage()               {}
func (*GetTagByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetTagByIdResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type GetBookByIdRequest struct {
	BookId string `protobuf:"bytes,1,opt,name=bookId" json:"bookId,omitempty"`
}

func (m *GetBookByIdRequest) Reset()                    { *m = GetBookByIdRequest{} }
func (m *GetBookByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBookByIdRequest) ProtoMessage()               {}
func (*GetBookByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetBookByIdRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

type GetBookByIdResponse struct {
	Id          string                         `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string                         `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Picture     string                         `protobuf:"bytes,3,opt,name=picture" json:"picture,omitempty"`
	Author      string                         `protobuf:"bytes,4,opt,name=author" json:"author,omitempty"`
	Description string                         `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Category    string                         `protobuf:"bytes,6,opt,name=category" json:"category,omitempty"`
	Catalog     []*GetBookByIdResponse_Catalog `protobuf:"bytes,11,rep,name=catalog" json:"catalog,omitempty"`
}

func (m *GetBookByIdResponse) Reset()                    { *m = GetBookByIdResponse{} }
func (m *GetBookByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBookByIdResponse) ProtoMessage()               {}
func (*GetBookByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetBookByIdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetBookByIdResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetBookByIdResponse) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *GetBookByIdResponse) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *GetBookByIdResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetBookByIdResponse) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *GetBookByIdResponse) GetCatalog() []*GetBookByIdResponse_Catalog {
	if m != nil {
		return m.Catalog
	}
	return nil
}

type GetBookByIdResponse_Catalog struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Chapter string `protobuf:"bytes,2,opt,name=chapter" json:"chapter,omitempty"`
}

func (m *GetBookByIdResponse_Catalog) Reset()                    { *m = GetBookByIdResponse_Catalog{} }
func (m *GetBookByIdResponse_Catalog) String() string            { return proto.CompactTextString(m) }
func (*GetBookByIdResponse_Catalog) ProtoMessage()               {}
func (*GetBookByIdResponse_Catalog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *GetBookByIdResponse_Catalog) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetBookByIdResponse_Catalog) GetChapter() string {
	if m != nil {
		return m.Chapter
	}
	return ""
}

type GetBookContentRequest struct {
	BookId string `protobuf:"bytes,1,opt,name=bookId" json:"bookId,omitempty"`
	MeauId string `protobuf:"bytes,2,opt,name=meauId" json:"meauId,omitempty"`
}

func (m *GetBookContentRequest) Reset()                    { *m = GetBookContentRequest{} }
func (m *GetBookContentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBookContentRequest) ProtoMessage()               {}
func (*GetBookContentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetBookContentRequest) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func (m *GetBookContentRequest) GetMeauId() string {
	if m != nil {
		return m.MeauId
	}
	return ""
}

type GetBookContentResponse struct {
	Contents []string `protobuf:"bytes,3,rep,name=contents" json:"contents,omitempty"`
}

func (m *GetBookContentResponse) Reset()                    { *m = GetBookContentResponse{} }
func (m *GetBookContentResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBookContentResponse) ProtoMessage()               {}
func (*GetBookContentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetBookContentResponse) GetContents() []string {
	if m != nil {
		return m.Contents
	}
	return nil
}

type SearchBookRequest struct {
	Keyword string `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`
}

func (m *SearchBookRequest) Reset()                    { *m = SearchBookRequest{} }
func (m *SearchBookRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchBookRequest) ProtoMessage()               {}
func (*SearchBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *SearchBookRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type SearchBookResponse struct {
	Books []*Book `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
}

func (m *SearchBookResponse) Reset()                    { *m = SearchBookResponse{} }
func (m *SearchBookResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchBookResponse) ProtoMessage()               {}
func (*SearchBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchBookResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type RegisterRequest struct {
	Account  string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RegisterRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Jwt string `protobuf:"bytes,1,opt,name=jwt" json:"jwt,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *RegisterResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type LoginRequest struct {
	Account  string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *LoginRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Jwt string `protobuf:"bytes,1,opt,name=jwt" json:"jwt,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *LoginResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type User struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Jwt     string `protobuf:"bytes,2,opt,name=jwt" json:"jwt,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *User) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *User) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type GetUserInfoRequest struct {
	User *User `protobuf:"bytes,100,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserInfoRequest) Reset()                    { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()               {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetUserInfoRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserInfoResponse struct {
	Username string                       `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Nickname string                       `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Current  *GetUserInfoResponse_Current `protobuf:"bytes,4,opt,name=current" json:"current,omitempty"`
}

func (m *GetUserInfoResponse) Reset()                    { *m = GetUserInfoResponse{} }
func (m *GetUserInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserInfoResponse) ProtoMessage()               {}
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetUserInfoResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserInfoResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetUserInfoResponse) GetCurrent() *GetUserInfoResponse_Current {
	if m != nil {
		return m.Current
	}
	return nil
}

type GetUserInfoResponse_Current struct {
	BookId     int32  `protobuf:"varint,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
	MenuId     int32  `protobuf:"varint,2,opt,name=menu_id,json=menuId" json:"menu_id,omitempty"`
	Page       int32  `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	HasHistory bool   `protobuf:"varint,4,opt,name=has_history,json=hasHistory" json:"has_history,omitempty"`
	LastTime   string `protobuf:"bytes,5,opt,name=last_time,json=lastTime" json:"last_time,omitempty"`
}

func (m *GetUserInfoResponse_Current) Reset()                    { *m = GetUserInfoResponse_Current{} }
func (m *GetUserInfoResponse_Current) String() string            { return proto.CompactTextString(m) }
func (*GetUserInfoResponse_Current) ProtoMessage()               {}
func (*GetUserInfoResponse_Current) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17, 0} }

func (m *GetUserInfoResponse_Current) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *GetUserInfoResponse_Current) GetMenuId() int32 {
	if m != nil {
		return m.MenuId
	}
	return 0
}

func (m *GetUserInfoResponse_Current) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUserInfoResponse_Current) GetHasHistory() bool {
	if m != nil {
		return m.HasHistory
	}
	return false
}

func (m *GetUserInfoResponse_Current) GetLastTime() string {
	if m != nil {
		return m.LastTime
	}
	return ""
}

type CollectBookRequest struct {
	User   *User  `protobuf:"bytes,100,opt,name=user" json:"user,omitempty"`
	BookId int32  `protobuf:"varint,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
	Tag    string `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
	Action string `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
}

func (m *CollectBookRequest) Reset()                    { *m = CollectBookRequest{} }
func (m *CollectBookRequest) String() string            { return proto.CompactTextString(m) }
func (*CollectBookRequest) ProtoMessage()               {}
func (*CollectBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CollectBookRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CollectBookRequest) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *CollectBookRequest) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *CollectBookRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type CollectBookResponse struct {
}

func (m *CollectBookResponse) Reset()                    { *m = CollectBookResponse{} }
func (m *CollectBookResponse) String() string            { return proto.CompactTextString(m) }
func (*CollectBookResponse) ProtoMessage()               {}
func (*CollectBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

type GetCollectedBookRequest struct {
	User *User `protobuf:"bytes,100,opt,name=user" json:"user,omitempty"`
}

func (m *GetCollectedBookRequest) Reset()                    { *m = GetCollectedBookRequest{} }
func (m *GetCollectedBookRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCollectedBookRequest) ProtoMessage()               {}
func (*GetCollectedBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *GetCollectedBookRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetCollectedBookResponse struct {
	Books []*Book                         `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
	Tag   []*GetCollectedBookResponse_Tag `protobuf:"bytes,2,rep,name=tag" json:"tag,omitempty"`
}

func (m *GetCollectedBookResponse) Reset()                    { *m = GetCollectedBookResponse{} }
func (m *GetCollectedBookResponse) String() string            { return proto.CompactTextString(m) }
func (*GetCollectedBookResponse) ProtoMessage()               {}
func (*GetCollectedBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *GetCollectedBookResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func (m *GetCollectedBookResponse) GetTag() []*GetCollectedBookResponse_Tag {
	if m != nil {
		return m.Tag
	}
	return nil
}

type GetCollectedBookResponse_Tag struct {
	BookId string `protobuf:"bytes,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
	Tag    string `protobuf:"bytes,2,opt,name=tag" json:"tag,omitempty"`
}

func (m *GetCollectedBookResponse_Tag) Reset()         { *m = GetCollectedBookResponse_Tag{} }
func (m *GetCollectedBookResponse_Tag) String() string { return proto.CompactTextString(m) }
func (*GetCollectedBookResponse_Tag) ProtoMessage()    {}
func (*GetCollectedBookResponse_Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{21, 0}
}

func (m *GetCollectedBookResponse_Tag) GetBookId() string {
	if m != nil {
		return m.BookId
	}
	return ""
}

func (m *GetCollectedBookResponse_Tag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type SetUserReadStatusRequest struct {
	User   *User `protobuf:"bytes,100,opt,name=user" json:"user,omitempty"`
	BookId int32 `protobuf:"varint,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
	MenuId int32 `protobuf:"varint,2,opt,name=menu_id,json=menuId" json:"menu_id,omitempty"`
	Page   int32 `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
}

func (m *SetUserReadStatusRequest) Reset()                    { *m = SetUserReadStatusRequest{} }
func (m *SetUserReadStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*SetUserReadStatusRequest) ProtoMessage()               {}
func (*SetUserReadStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *SetUserReadStatusRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SetUserReadStatusRequest) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *SetUserReadStatusRequest) GetMenuId() int32 {
	if m != nil {
		return m.MenuId
	}
	return 0
}

func (m *SetUserReadStatusRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type SetUserReadStatusResponse struct {
}

func (m *SetUserReadStatusResponse) Reset()                    { *m = SetUserReadStatusResponse{} }
func (m *SetUserReadStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*SetUserReadStatusResponse) ProtoMessage()               {}
func (*SetUserReadStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

type GetUserReadStatusRequest struct {
	User   *User `protobuf:"bytes,100,opt,name=user" json:"user,omitempty"`
	BookId int32 `protobuf:"varint,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
}

func (m *GetUserReadStatusRequest) Reset()                    { *m = GetUserReadStatusRequest{} }
func (m *GetUserReadStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserReadStatusRequest) ProtoMessage()               {}
func (*GetUserReadStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *GetUserReadStatusRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *GetUserReadStatusRequest) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type GetUserReadStatusResponse struct {
	BookId     int32  `protobuf:"varint,1,opt,name=book_id,json=bookId" json:"book_id,omitempty"`
	MenuId     int32  `protobuf:"varint,2,opt,name=menu_id,json=menuId" json:"menu_id,omitempty"`
	Page       int32  `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	HasHistory bool   `protobuf:"varint,4,opt,name=has_history,json=hasHistory" json:"has_history,omitempty"`
	LastTime   string `protobuf:"bytes,5,opt,name=last_time,json=lastTime" json:"last_time,omitempty"`
}

func (m *GetUserReadStatusResponse) Reset()                    { *m = GetUserReadStatusResponse{} }
func (m *GetUserReadStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserReadStatusResponse) ProtoMessage()               {}
func (*GetUserReadStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GetUserReadStatusResponse) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *GetUserReadStatusResponse) GetMenuId() int32 {
	if m != nil {
		return m.MenuId
	}
	return 0
}

func (m *GetUserReadStatusResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUserReadStatusResponse) GetHasHistory() bool {
	if m != nil {
		return m.HasHistory
	}
	return false
}

func (m *GetUserReadStatusResponse) GetLastTime() string {
	if m != nil {
		return m.LastTime
	}
	return ""
}

type GetUserRecommendBookRequest struct {
	User *User `protobuf:"bytes,100,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserRecommendBookRequest) Reset()                    { *m = GetUserRecommendBookRequest{} }
func (m *GetUserRecommendBookRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRecommendBookRequest) ProtoMessage()               {}
func (*GetUserRecommendBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *GetUserRecommendBookRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserRecommendBookResponse struct {
	Books []*Book `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
}

func (m *GetUserRecommendBookResponse) Reset()                    { *m = GetUserRecommendBookResponse{} }
func (m *GetUserRecommendBookResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserRecommendBookResponse) ProtoMessage()               {}
func (*GetUserRecommendBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *GetUserRecommendBookResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func init() {
	proto.RegisterType((*GetTagsRequest)(nil), "go.micro.srv.book_server_v2.GetTagsRequest")
	proto.RegisterType((*GetTagsResponse)(nil), "go.micro.srv.book_server_v2.GetTagsResponse")
	proto.RegisterType((*GetTagsResponse_Tag)(nil), "go.micro.srv.book_server_v2.GetTagsResponse.Tag")
	proto.RegisterType((*GetTagByIdRequest)(nil), "go.micro.srv.book_server_v2.GetTagByIdRequest")
	proto.RegisterType((*Book)(nil), "go.micro.srv.book_server_v2.Book")
	proto.RegisterType((*GetTagByIdResponse)(nil), "go.micro.srv.book_server_v2.GetTagByIdResponse")
	proto.RegisterType((*GetBookByIdRequest)(nil), "go.micro.srv.book_server_v2.GetBookByIdRequest")
	proto.RegisterType((*GetBookByIdResponse)(nil), "go.micro.srv.book_server_v2.GetBookByIdResponse")
	proto.RegisterType((*GetBookByIdResponse_Catalog)(nil), "go.micro.srv.book_server_v2.GetBookByIdResponse.Catalog")
	proto.RegisterType((*GetBookContentRequest)(nil), "go.micro.srv.book_server_v2.GetBookContentRequest")
	proto.RegisterType((*GetBookContentResponse)(nil), "go.micro.srv.book_server_v2.GetBookContentResponse")
	proto.RegisterType((*SearchBookRequest)(nil), "go.micro.srv.book_server_v2.SearchBookRequest")
	proto.RegisterType((*SearchBookResponse)(nil), "go.micro.srv.book_server_v2.SearchBookResponse")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.srv.book_server_v2.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.srv.book_server_v2.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.book_server_v2.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.srv.book_server_v2.LoginResponse")
	proto.RegisterType((*User)(nil), "go.micro.srv.book_server_v2.User")
	proto.RegisterType((*GetUserInfoRequest)(nil), "go.micro.srv.book_server_v2.GetUserInfoRequest")
	proto.RegisterType((*GetUserInfoResponse)(nil), "go.micro.srv.book_server_v2.GetUserInfoResponse")
	proto.RegisterType((*GetUserInfoResponse_Current)(nil), "go.micro.srv.book_server_v2.GetUserInfoResponse.Current")
	proto.RegisterType((*CollectBookRequest)(nil), "go.micro.srv.book_server_v2.CollectBookRequest")
	proto.RegisterType((*CollectBookResponse)(nil), "go.micro.srv.book_server_v2.CollectBookResponse")
	proto.RegisterType((*GetCollectedBookRequest)(nil), "go.micro.srv.book_server_v2.GetCollectedBookRequest")
	proto.RegisterType((*GetCollectedBookResponse)(nil), "go.micro.srv.book_server_v2.GetCollectedBookResponse")
	proto.RegisterType((*GetCollectedBookResponse_Tag)(nil), "go.micro.srv.book_server_v2.GetCollectedBookResponse.Tag")
	proto.RegisterType((*SetUserReadStatusRequest)(nil), "go.micro.srv.book_server_v2.SetUserReadStatusRequest")
	proto.RegisterType((*SetUserReadStatusResponse)(nil), "go.micro.srv.book_server_v2.SetUserReadStatusResponse")
	proto.RegisterType((*GetUserReadStatusRequest)(nil), "go.micro.srv.book_server_v2.GetUserReadStatusRequest")
	proto.RegisterType((*GetUserReadStatusResponse)(nil), "go.micro.srv.book_server_v2.GetUserReadStatusResponse")
	proto.RegisterType((*GetUserRecommendBookRequest)(nil), "go.micro.srv.book_server_v2.GetUserRecommendBookRequest")
	proto.RegisterType((*GetUserRecommendBookResponse)(nil), "go.micro.srv.book_server_v2.GetUserRecommendBookResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Publisher API

type Publisher interface {
	Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error
}

type publisher struct {
	c     client.Client
	topic string
}

func (p *publisher) Publish(ctx context.Context, msg interface{}, opts ...client.PublishOption) error {
	return p.c.Publish(ctx, p.c.NewPublication(p.topic, msg), opts...)
}

func NewPublisher(topic string, c client.Client) Publisher {
	if c == nil {
		c = client.NewClient()
	}
	return &publisher{c, topic}
}

// Subscriber API

func RegisterSubscriber(topic string, s server.Server, h interface{}, opts ...server.SubscriberOption) error {
	return s.Subscribe(s.NewSubscriber(topic, h, opts...))
}

// Client API for BookService service

type BookServiceClient interface {
	GetTags(ctx context.Context, in *GetTagsRequest, opts ...client.CallOption) (*GetTagsResponse, error)
	GetTagById(ctx context.Context, in *GetTagByIdRequest, opts ...client.CallOption) (*GetTagByIdResponse, error)
	GetBookById(ctx context.Context, in *GetBookByIdRequest, opts ...client.CallOption) (*GetBookByIdResponse, error)
	GetBookContent(ctx context.Context, in *GetBookContentRequest, opts ...client.CallOption) (*GetBookContentResponse, error)
	SearchBook(ctx context.Context, in *SearchBookRequest, opts ...client.CallOption) (*SearchBookResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...client.CallOption) (*GetUserInfoResponse, error)
	CollectBook(ctx context.Context, in *CollectBookRequest, opts ...client.CallOption) (*CollectBookResponse, error)
	GetCollectedBook(ctx context.Context, in *GetCollectedBookRequest, opts ...client.CallOption) (*GetCollectedBookResponse, error)
	SetUserReadStatus(ctx context.Context, in *SetUserReadStatusRequest, opts ...client.CallOption) (*SetUserReadStatusResponse, error)
	GetUserReadStatus(ctx context.Context, in *GetUserReadStatusRequest, opts ...client.CallOption) (*GetUserReadStatusResponse, error)
	GetUserRecommendBook(ctx context.Context, in *GetUserRecommendBookRequest, opts ...client.CallOption) (*GetUserRecommendBookResponse, error)
}

type bookServiceClient struct {
	c           client.Client
	serviceName string
}

func NewBookServiceClient(serviceName string, c client.Client) BookServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.book_server_v2"
	}
	return &bookServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *bookServiceClient) GetTags(ctx context.Context, in *GetTagsRequest, opts ...client.CallOption) (*GetTagsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.GetTags", in)
	out := new(GetTagsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetTagById(ctx context.Context, in *GetTagByIdRequest, opts ...client.CallOption) (*GetTagByIdResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.GetTagById", in)
	out := new(GetTagByIdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBookById(ctx context.Context, in *GetBookByIdRequest, opts ...client.CallOption) (*GetBookByIdResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.GetBookById", in)
	out := new(GetBookByIdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetBookContent(ctx context.Context, in *GetBookContentRequest, opts ...client.CallOption) (*GetBookContentResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.GetBookContent", in)
	out := new(GetBookContentResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) SearchBook(ctx context.Context, in *SearchBookRequest, opts ...client.CallOption) (*SearchBookResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.SearchBook", in)
	out := new(SearchBookResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...client.CallOption) (*RegisterResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.Register", in)
	out := new(RegisterResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...client.CallOption) (*GetUserInfoResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.GetUserInfo", in)
	out := new(GetUserInfoResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) CollectBook(ctx context.Context, in *CollectBookRequest, opts ...client.CallOption) (*CollectBookResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.CollectBook", in)
	out := new(CollectBookResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetCollectedBook(ctx context.Context, in *GetCollectedBookRequest, opts ...client.CallOption) (*GetCollectedBookResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.GetCollectedBook", in)
	out := new(GetCollectedBookResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) SetUserReadStatus(ctx context.Context, in *SetUserReadStatusRequest, opts ...client.CallOption) (*SetUserReadStatusResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.SetUserReadStatus", in)
	out := new(SetUserReadStatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetUserReadStatus(ctx context.Context, in *GetUserReadStatusRequest, opts ...client.CallOption) (*GetUserReadStatusResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.GetUserReadStatus", in)
	out := new(GetUserReadStatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetUserRecommendBook(ctx context.Context, in *GetUserRecommendBookRequest, opts ...client.CallOption) (*GetUserRecommendBookResponse, error) {
	req := c.c.NewRequest(c.serviceName, "BookService.GetUserRecommendBook", in)
	out := new(GetUserRecommendBookResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BookService service

type BookServiceHandler interface {
	GetTags(context.Context, *GetTagsRequest, *GetTagsResponse) error
	GetTagById(context.Context, *GetTagByIdRequest, *GetTagByIdResponse) error
	GetBookById(context.Context, *GetBookByIdRequest, *GetBookByIdResponse) error
	GetBookContent(context.Context, *GetBookContentRequest, *GetBookContentResponse) error
	SearchBook(context.Context, *SearchBookRequest, *SearchBookResponse) error
	Register(context.Context, *RegisterRequest, *RegisterResponse) error
	Login(context.Context, *LoginRequest, *LoginResponse) error
	GetUserInfo(context.Context, *GetUserInfoRequest, *GetUserInfoResponse) error
	CollectBook(context.Context, *CollectBookRequest, *CollectBookResponse) error
	GetCollectedBook(context.Context, *GetCollectedBookRequest, *GetCollectedBookResponse) error
	SetUserReadStatus(context.Context, *SetUserReadStatusRequest, *SetUserReadStatusResponse) error
	GetUserReadStatus(context.Context, *GetUserReadStatusRequest, *GetUserReadStatusResponse) error
	GetUserRecommendBook(context.Context, *GetUserRecommendBookRequest, *GetUserRecommendBookResponse) error
}

func RegisterBookServiceHandler(s server.Server, hdlr BookServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&BookService{hdlr}, opts...))
}

type BookService struct {
	BookServiceHandler
}

func (h *BookService) GetTags(ctx context.Context, in *GetTagsRequest, out *GetTagsResponse) error {
	return h.BookServiceHandler.GetTags(ctx, in, out)
}

func (h *BookService) GetTagById(ctx context.Context, in *GetTagByIdRequest, out *GetTagByIdResponse) error {
	return h.BookServiceHandler.GetTagById(ctx, in, out)
}

func (h *BookService) GetBookById(ctx context.Context, in *GetBookByIdRequest, out *GetBookByIdResponse) error {
	return h.BookServiceHandler.GetBookById(ctx, in, out)
}

func (h *BookService) GetBookContent(ctx context.Context, in *GetBookContentRequest, out *GetBookContentResponse) error {
	return h.BookServiceHandler.GetBookContent(ctx, in, out)
}

func (h *BookService) SearchBook(ctx context.Context, in *SearchBookRequest, out *SearchBookResponse) error {
	return h.BookServiceHandler.SearchBook(ctx, in, out)
}

func (h *BookService) Register(ctx context.Context, in *RegisterRequest, out *RegisterResponse) error {
	return h.BookServiceHandler.Register(ctx, in, out)
}

func (h *BookService) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.BookServiceHandler.Login(ctx, in, out)
}

func (h *BookService) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, out *GetUserInfoResponse) error {
	return h.BookServiceHandler.GetUserInfo(ctx, in, out)
}

func (h *BookService) CollectBook(ctx context.Context, in *CollectBookRequest, out *CollectBookResponse) error {
	return h.BookServiceHandler.CollectBook(ctx, in, out)
}

func (h *BookService) GetCollectedBook(ctx context.Context, in *GetCollectedBookRequest, out *GetCollectedBookResponse) error {
	return h.BookServiceHandler.GetCollectedBook(ctx, in, out)
}

func (h *BookService) SetUserReadStatus(ctx context.Context, in *SetUserReadStatusRequest, out *SetUserReadStatusResponse) error {
	return h.BookServiceHandler.SetUserReadStatus(ctx, in, out)
}

func (h *BookService) GetUserReadStatus(ctx context.Context, in *GetUserReadStatusRequest, out *GetUserReadStatusResponse) error {
	return h.BookServiceHandler.GetUserReadStatus(ctx, in, out)
}

func (h *BookService) GetUserRecommendBook(ctx context.Context, in *GetUserRecommendBookRequest, out *GetUserRecommendBookResponse) error {
	return h.BookServiceHandler.GetUserRecommendBook(ctx, in, out)
}

func init() {
	proto.RegisterFile("git.oschina.net/wkc/book-server-v2/proto/v1/BookService.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 1296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0xdf, 0x6e, 0x1b, 0xc5,
	0x17, 0xd6, 0xda, 0x4e, 0xec, 0x1c, 0xb7, 0x89, 0x3b, 0x6d, 0x9a, 0xed, 0xba, 0xd2, 0xcf, 0x9d,
	0xfe, 0x90, 0x4a, 0xdb, 0xec, 0x16, 0xb7, 0x85, 0x16, 0x89, 0x9b, 0xa6, 0x52, 0x88, 0x0a, 0x08,
	0x6d, 0x82, 0xb8, 0xb4, 0xa6, 0xeb, 0x61, 0xbd, 0x8d, 0xbd, 0x63, 0x76, 0xc6, 0xae, 0xa2, 0x28,
	0x12, 0x42, 0x48, 0xbd, 0xa1, 0xdc, 0x70, 0x81, 0xe0, 0x02, 0xae, 0xa0, 0xd7, 0xf0, 0x28, 0xf0,
	0x0a, 0x3c, 0x00, 0x8f, 0x80, 0x66, 0x76, 0xd6, 0x5e, 0xaf, 0xff, 0x27, 0x80, 0x7a, 0xb7, 0x67,
	0x66, 0xce, 0xf9, 0xbe, 0x73, 0xe6, 0xcc, 0xcc, 0x67, 0xc3, 0x7b, 0x7e, 0x20, 0x6c, 0xc6, 0xbd,
	0x56, 0x10, 0x12, 0x3b, 0xa4, 0xc2, 0x79, 0x7e, 0xe8, 0x39, 0x4f, 0x19, 0x3b, 0xdc, 0xe6, 0x34,
	0xea, 0xd3, 0x68, 0xbb, 0x5f, 0x77, 0xba, 0x11, 0x13, 0xcc, 0xe9, 0xbf, 0xe5, 0x3c, 0x62, 0xec,
	0x70, 0x9f, 0x46, 0xfd, 0xc0, 0xa3, 0xb6, 0x1a, 0x44, 0x55, 0x9f, 0xd9, 0x9d, 0xc0, 0x8b, 0x98,
	0xcd, 0xa3, 0xbe, 0x2d, 0xfd, 0x1a, 0xb1, 0x5f, 0xa3, 0x5f, 0xb7, 0xae, 0xfa, 0x8c, 0xf9, 0x6d,
	0xea, 0x90, 0x6e, 0xe0, 0x90, 0x30, 0x64, 0x82, 0x88, 0x80, 0x85, 0x3c, 0x76, 0xc5, 0x15, 0x58,
	0xdf, 0xa5, 0xe2, 0x80, 0xf8, 0xdc, 0xa5, 0x9f, 0xf7, 0x28, 0x17, 0xf8, 0x95, 0x01, 0x1b, 0x83,
	0x21, 0xde, 0x65, 0x21, 0xa7, 0xe8, 0x31, 0x14, 0x04, 0xf1, 0xb9, 0x69, 0xd4, 0xf2, 0x37, 0xca,
	0xf5, 0x3b, 0xf6, 0x0c, 0x3c, 0x3b, 0xe3, 0x6b, 0x1f, 0x10, 0xdf, 0x55, 0xde, 0xd6, 0x47, 0x90,
	0x3f, 0x20, 0x3e, 0x5a, 0x87, 0x5c, 0xd0, 0x34, 0x8d, 0x9a, 0x71, 0x63, 0xcd, 0xcd, 0x05, 0x4d,
	0x64, 0x41, 0xc9, 0x23, 0x82, 0xfa, 0x2c, 0x3a, 0x32, 0x73, 0x6a, 0x74, 0x60, 0xa3, 0x2a, 0xac,
	0xc9, 0xf0, 0xbc, 0xe1, 0x85, 0xc2, 0xcc, 0xd7, 0x8c, 0x1b, 0x2b, 0x6e, 0x49, 0x0d, 0xec, 0x84,
	0x02, 0x5f, 0x87, 0x0b, 0x31, 0xd8, 0xa3, 0xa3, 0xbd, 0xa6, 0xa6, 0x9f, 0x8d, 0x8e, 0x7f, 0x30,
	0xa0, 0x20, 0x2b, 0x36, 0x06, 0x8b, 0xa0, 0x10, 0x92, 0x0e, 0xd5, 0x90, 0xea, 0x1b, 0x99, 0x50,
	0xec, 0x06, 0x9e, 0xe8, 0x45, 0x54, 0x81, 0xad, 0xb9, 0x89, 0x89, 0x2e, 0xc3, 0x2a, 0xe9, 0x89,
	0x16, 0x8b, 0xcc, 0x82, 0x9a, 0xd0, 0x16, 0xaa, 0x41, 0xb9, 0x49, 0xb9, 0x17, 0x05, 0x5d, 0x59,
	0x55, 0x73, 0x45, 0x4d, 0xa6, 0x87, 0x46, 0xd2, 0x5b, 0x1d, 0x4d, 0x0f, 0x7f, 0x08, 0x28, 0x9d,
	0x81, 0xae, 0xf6, 0x3b, 0xb0, 0xa2, 0x72, 0xd4, 0xe5, 0xbe, 0x36, 0xb3, 0xdc, 0x32, 0x37, 0x37,
	0x5e, 0x8f, 0x6f, 0xab, 0x70, 0x72, 0x24, 0x5d, 0x91, 0xcb, 0xb0, 0x2a, 0xa7, 0xf7, 0x92, 0xe4,
	0xb5, 0x85, 0x7f, 0xcb, 0xc1, 0xc5, 0x91, 0xe5, 0x1a, 0xfe, 0x35, 0x2c, 0x14, 0x72, 0xa1, 0xe8,
	0x11, 0x41, 0xda, 0xcc, 0x37, 0xcb, 0xaa, 0x28, 0x0f, 0xe6, 0xf5, 0x60, 0x36, 0x2d, 0x7b, 0x27,
	0xf6, 0x77, 0x93, 0x40, 0xd6, 0x5d, 0x28, 0xea, 0xb1, 0xb1, 0x94, 0x4d, 0x28, 0x7a, 0x2d, 0xd2,
	0x15, 0x34, 0xd2, 0x59, 0x27, 0x26, 0xde, 0x85, 0x4d, 0x1d, 0x7c, 0x87, 0x85, 0x82, 0x86, 0x62,
	0x4e, 0x95, 0xe5, 0x78, 0x87, 0x92, 0xde, 0x5e, 0x53, 0x47, 0xd2, 0x16, 0xbe, 0x07, 0x97, 0xb3,
	0x81, 0x74, 0xfd, 0x65, 0x1d, 0xe2, 0x21, 0x6e, 0xe6, 0x6b, 0x79, 0x55, 0x07, 0x6d, 0xe3, 0x6d,
	0xb8, 0xb0, 0x4f, 0x49, 0xe4, 0xb5, 0xd4, 0xb6, 0x6b, 0x68, 0x13, 0x8a, 0x87, 0xf4, 0xe8, 0x39,
	0x8b, 0x12, 0xec, 0xc4, 0x94, 0xfd, 0x95, 0x5e, 0x7e, 0xd6, 0xfe, 0xf2, 0x60, 0xc3, 0xa5, 0x7e,
	0xc0, 0x05, 0x8d, 0x52, 0xd8, 0xc4, 0xf3, 0x58, 0x2f, 0x14, 0x09, 0xb6, 0x36, 0x65, 0x1a, 0x61,
	0xe0, 0x1d, 0xa6, 0x5a, 0x67, 0x60, 0xcb, 0xb9, 0x2e, 0xe1, 0x5c, 0x51, 0x8e, 0xfb, 0x67, 0x60,
	0xe3, 0xff, 0x43, 0x65, 0x08, 0xa2, 0x19, 0x57, 0x20, 0xff, 0xec, 0x79, 0x82, 0x20, 0x3f, 0xf1,
	0x63, 0x38, 0xf7, 0x01, 0xf3, 0x83, 0x70, 0x21, 0x1e, 0x53, 0xb1, 0xae, 0xc1, 0x79, 0x1d, 0x65,
	0x2a, 0x50, 0x1d, 0x0a, 0x9f, 0x70, 0x1a, 0xcd, 0x00, 0xd0, 0x3e, 0xb9, 0xa1, 0xcf, 0x13, 0x75,
	0x0e, 0xa5, 0xdb, 0x5e, 0xf8, 0x19, 0x4b, 0x28, 0xde, 0x87, 0x42, 0x8f, 0xd3, 0xc8, 0x6c, 0xd6,
	0x8c, 0xb9, 0x55, 0x97, 0xbe, 0xae, 0x5a, 0x8e, 0x7f, 0x8d, 0x8f, 0xe9, 0x30, 0xda, 0xb0, 0x4d,
	0xe4, 0xbc, 0xaa, 0x6f, 0xcc, 0x68, 0x60, 0xcf, 0xac, 0xbd, 0x3c, 0x4a, 0xbd, 0x28, 0xa2, 0xa1,
	0x50, 0x27, 0x74, 0x81, 0xa3, 0x94, 0x85, 0xb6, 0x77, 0x62, 0x7f, 0x37, 0x09, 0x64, 0xbd, 0x34,
	0xa0, 0xa8, 0x07, 0xd1, 0x16, 0x14, 0x55, 0x08, 0x7d, 0xa0, 0x56, 0x06, 0x27, 0x61, 0x0b, 0x8a,
	0x1d, 0x1a, 0xf6, 0xe4, 0x44, 0x2e, 0x9e, 0x90, 0xe6, 0x9e, 0xba, 0x60, 0xba, 0xc4, 0xa7, 0xfa,
	0x7e, 0x57, 0xdf, 0xe8, 0x7f, 0x50, 0x6e, 0x11, 0xde, 0x68, 0x05, 0x5c, 0xc8, 0xfb, 0x40, 0x32,
	0x2d, 0xb9, 0xd0, 0x22, 0xfc, 0xfd, 0x78, 0x44, 0xbe, 0x0c, 0x6d, 0xc2, 0x45, 0x43, 0x04, 0x1d,
	0xaa, 0x6f, 0x93, 0x92, 0x1c, 0x38, 0x08, 0x3a, 0x14, 0x7f, 0x63, 0x00, 0xda, 0x61, 0xed, 0x36,
	0xf5, 0x44, 0xfa, 0xa0, 0x9c, 0x6e, 0x07, 0xa6, 0x67, 0x54, 0x81, 0xbc, 0x20, 0x7e, 0xb2, 0xf3,
	0x82, 0xf8, 0xea, 0xf6, 0xf3, 0xd4, 0x05, 0x97, 0xd7, 0xb7, 0x9f, 0xb2, 0xf0, 0x26, 0x5c, 0x1c,
	0xe1, 0x13, 0x17, 0x12, 0x7f, 0x0c, 0x5b, 0xbb, 0x54, 0xe8, 0x19, 0xda, 0x3c, 0x3b, 0x57, 0xfc,
	0xbb, 0x01, 0xe6, 0x78, 0xc8, 0x33, 0x1e, 0x7c, 0xf4, 0x24, 0x49, 0x54, 0xba, 0x3d, 0x9c, 0xd7,
	0x2f, 0x13, 0xc1, 0x95, 0x0e, 0x90, 0x51, 0xac, 0x3b, 0xb1, 0x0c, 0xc8, 0x54, 0x75, 0x6d, 0x7a,
	0x55, 0xf1, 0x77, 0x06, 0x98, 0xfb, 0x71, 0x1f, 0xba, 0x94, 0x34, 0xf7, 0x05, 0x11, 0x3d, 0xfe,
	0x6f, 0x6d, 0xea, 0x32, 0x6d, 0x8a, 0xab, 0x70, 0x65, 0x02, 0x31, 0xbd, 0xbb, 0xcf, 0xd4, 0x56,
	0xfc, 0x27, 0xac, 0xf1, 0x4f, 0x06, 0x5c, 0xd9, 0x9d, 0xc6, 0xe4, 0xb5, 0x38, 0x93, 0x07, 0x50,
	0x1d, 0x10, 0xf4, 0x58, 0xa7, 0x43, 0xc3, 0x7f, 0xa2, 0xdf, 0x3f, 0x85, 0xab, 0x93, 0xa3, 0x9e,
	0xb1, 0xe5, 0xeb, 0x7f, 0xad, 0x43, 0x39, 0xa5, 0xb4, 0x51, 0x1f, 0x8a, 0x5a, 0xd9, 0xa2, 0x5b,
	0x8b, 0xe9, 0x5f, 0x95, 0x97, 0x75, 0x7b, 0x19, 0xb1, 0x8c, 0x2b, 0x5f, 0xfe, 0xf1, 0xe7, 0xb7,
	0x39, 0x40, 0x25, 0xa7, 0x5f, 0x77, 0xa4, 0x68, 0x46, 0x5f, 0x19, 0x00, 0x43, 0x8d, 0x88, 0xec,
	0x05, 0xc2, 0xa5, 0xc4, 0x9f, 0xe5, 0x2c, 0xbc, 0x5e, 0x33, 0xd8, 0x54, 0x0c, 0x36, 0xd0, 0xf9,
	0x84, 0x81, 0x73, 0x1c, 0x34, 0x4f, 0xd0, 0xd7, 0x06, 0x94, 0x53, 0xaa, 0x0a, 0x39, 0x8b, 0xeb,
	0xaf, 0x98, 0xc8, 0x9d, 0x65, 0x05, 0x1b, 0xb6, 0x14, 0x93, 0x4b, 0x08, 0x49, 0x26, 0x6a, 0x53,
	0x9c, 0xe3, 0xb8, 0x6d, 0x4f, 0xd0, 0x2f, 0x86, 0xfa, 0xdd, 0x92, 0x92, 0x4f, 0xa8, 0xbe, 0x08,
	0xc0, 0xa8, 0x68, 0xb3, 0xee, 0x2e, 0xe5, 0xa3, 0x79, 0xdd, 0x52, 0xbc, 0xde, 0x40, 0xd7, 0xc7,
	0x79, 0x39, 0x5a, 0xa8, 0x39, 0xc7, 0xb1, 0xca, 0x3b, 0x41, 0x2f, 0x0c, 0x80, 0xa1, 0x04, 0x9b,
	0xb3, 0x7d, 0x63, 0xd2, 0x6e, 0xce, 0xf6, 0x8d, 0x6b, 0x3b, 0x6c, 0x2a, 0x72, 0x08, 0x55, 0x24,
	0x39, 0xae, 0xe6, 0x63, 0x8e, 0xe8, 0x0b, 0x03, 0x4a, 0x89, 0xb0, 0x42, 0xb3, 0xbb, 0x32, 0x23,
	0xf2, 0xac, 0xed, 0x05, 0x57, 0x6b, 0x0e, 0x5b, 0x8a, 0xc3, 0x05, 0x7c, 0x4e, 0x72, 0x88, 0xf4,
	0xec, 0xbb, 0xc6, 0x4d, 0x24, 0x60, 0x45, 0xc9, 0x2d, 0xf4, 0xe6, 0xcc, 0x80, 0x69, 0x61, 0x67,
	0xdd, 0x5c, 0x64, 0xa9, 0x06, 0xbe, 0xa4, 0x80, 0xd7, 0xf1, 0x9a, 0x04, 0x6e, 0xcb, 0x29, 0x89,
	0xfa, 0x22, 0x6e, 0xdd, 0x44, 0xc5, 0xcc, 0x6f, 0xdd, 0x8c, 0x70, 0x9b, 0xdf, 0xba, 0x59, 0x81,
	0x34, 0x7a, 0x88, 0xe4, 0x3d, 0xe5, 0x04, 0x12, 0xf9, 0xa5, 0x01, 0xe5, 0x94, 0x0c, 0x98, 0xc3,
	0x64, 0x5c, 0xc0, 0xcc, 0x61, 0x32, 0x49, 0x61, 0x54, 0x15, 0x93, 0x4d, 0x5c, 0x19, 0x30, 0xf1,
	0xe2, 0x55, 0xb2, 0x32, 0xdf, 0x1b, 0x50, 0xc9, 0xbe, 0xd7, 0xe8, 0xde, 0x92, 0xcf, 0x7b, 0xcc,
	0xec, 0xfe, 0xa9, 0x44, 0xc1, 0x68, 0xbb, 0xa6, 0xe9, 0xa1, 0x1f, 0x0d, 0xf9, 0x53, 0x27, 0xf3,
	0xa0, 0xa1, 0xfb, 0x73, 0xce, 0xc3, 0xe4, 0xd7, 0xd6, 0x7a, 0x7b, 0x59, 0xb7, 0xd1, 0x2b, 0x08,
	0x6f, 0x0c, 0xe8, 0x71, 0xb5, 0x40, 0x16, 0xef, 0x67, 0x43, 0xfd, 0xfd, 0xb0, 0x14, 0xc1, 0xdd,
	0xd3, 0x11, 0x9c, 0xfa, 0xb0, 0xe3, 0x6b, 0x8a, 0x60, 0x15, 0x5d, 0xc9, 0x10, 0x8c, 0x6f, 0xa4,
	0x86, 0xbc, 0xb9, 0x5f, 0x19, 0x70, 0x69, 0xd2, 0x13, 0x89, 0x1e, 0x2c, 0x86, 0x39, 0xfe, 0x56,
	0x5b, 0x0f, 0x4f, 0xe1, 0x39, 0xe9, 0x52, 0x57, 0x84, 0xa3, 0x64, 0xdd, 0xd3, 0x55, 0xf5, 0x97,
	0xd4, 0xdd, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x0c, 0x09, 0x06, 0x0e, 0x13, 0x00, 0x00,
}
